name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Enable tmate debugging session'
        required: false
        default: 'false'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            python3-venv \
            python3-pip \
            git pybind11-dev python3-pybind11 libboost-all-dev

      - name: Install Google Test
        run: |
          git clone https://github.com/google/googletest.git
          cd googletest
          mkdir build && cd build
          cmake ..
          make -j$(nproc)
          sudo make install

      - name: Build CMake project
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DLMP_ENABLE_CUDA=OFF -DLMP_ENABLE_TEST=ON -DLMP_ENABLE_COVERAGE=OFF -DLMP_ENABLE_BENCH=OFF

      - name: Build lamppp module
        run: cmake --build build --config Debug --parallel

      - name: Run GTests
        run: |
          build/tests/autograd_tests
          build/tests/tensor_tests

      - name: Setup Python 3
        uses: actions/setup-python@v4
        with:
          python-version: ">=3.11"

      - name: Install Python dependencies
        run: |
          pip install uv
          uv lock
          uv sync --extra cpu

      - name: Install Pylamp
        run: uv pip install .

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          limit-access-to-actor: true

      - name: Run tests
        run: uv run pytest tests/stress/pytorch_stress_test.py

      # TODO: can probably upload some artifact here to save time, idc rn